pool:
  vmImage: windows-2022
trigger:
  branches:
    include:
      - "*"
variables:
  nextRelease: unknown
steps:
  - task: PowerShell@2
    displayName: "Install semantic-release"
    inputs:
      targetType: "inline"
      script: |
        npm install -g semantic-release @semantic-release/git semantic-release-ado @semantic-release/release-notes-generator
  - task: PowerShell@2
    displayName: "Upgrade version"
    inputs:
      targetType: "inline"
      script: |
        semantic-release

  - powershell: |
      echo "##vso[task.setvariable variable=versionNumber;isOutput=true]$(nextRelease)"
      name: setOutputVar
      
  - script: echo $(nextRelease)
    displayName: 'Show next version'
  
  - task: DotNetCoreCLI@2
    displayName: Build the project
    inputs:
      command: "build"
      projects: |
        **/*.csproj
  - task: DotNetCoreCLI@2
    displayName: Package the project
    inputs:
      command: "pack"
      packagesToPack: "**/Smartbills.NET.csproj"
      versioningScheme: "byEnvVar"
      versionEnvVar: "nextRelease"
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(Pipeline.Workspace)"
      publishLocation: "pipeline"
