pool: 
  vmImage: windows-2022
trigger:
  branches:
    include:
    - '*'

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        npx -p semantic-release 
        -p @semantic-release/git
        -p semantic-release-ado
        -p @semantic-release/release-notes-generator
        semantic-release
  - task: DotNetCoreCLI@2
    displayName: Build the project
    inputs:
      command: 'build'
      projects: |
        **/*.csproj
  - task: DotNetCoreCLI@2
    displayName: Package the project
    inputs:
      command: 'pack'
      packagesToPack: '**/Smartbills.NET.csproj'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'SEMANTIC_VERSION'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      publishLocation: 'pipeline'