name: Build

on:
  push:
    branches: [master, main, dev]
  pull_request:
    branches: [master, main, dev]

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: |
          dotnet restore Smartbills.NET/Smartbills.NET.csproj

      - name: Build
        run: |
          dotnet build Smartbills.NET/Smartbills.NET.csproj --configuration Release --no-restore

      - name: Package the project
        run: |
          dotnet pack Smartbills.NET/Smartbills.NET.csproj --configuration Release --no-build

      - name: Upload build artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            Smartbills.NET/bin/Release/
          retention-days: 1
          compression-level: 6
