name: Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: Smartbills.NET/packages.lock.json

    
      - name: Restore dependencies
        run: |
          dotnet restore Smartbills.NET/Smartbills.NET.csproj --locked-mode
          dotnet restore Smartbills.NET.AspNetCore/Smartbills.NET.AspNetCore.csproj --locked-mode

      - name: Build
        run: |
          dotnet build Smartbills.NET/Smartbills.NET.csproj --configuration Release --no-restore
          dotnet build Smartbills.NET.AspNetCore/Smartbills.NET.AspNetCore.csproj --configuration Release --no-restore

      - name: Upload build artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            Smartbills.NET/bin/Release/
            Smartbills.NET.AspNetCore/bin/Release/
          retention-days: 1
          compression-level: 6
